# Generated by Django 5.0.6 on 2024-07-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_master',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('role_name', models.CharField(max_length=30)),
            ],
        ),
    ]
