# Generated by Django 5.0.6 on 2024-07-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_contact',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=30)),
            ],
        ),
    ]
